#!/usr/bin/env perl

use strict;
use warnings;

use App::stew::util qw(error);
use App::stew::cmd::install;
use App::stew::cmd::build;
use App::stew::cmd::list_installed;
use App::stew::cmd::uninstall;
use App::stew::cmd::exec;

my $command = shift @ARGV;

if (!$command) {
}
elsif ($command eq 'install') {
    App::stew::cmd::install->new()->run(@ARGV);
}
elsif ($command eq 'build') {
    App::stew::cmd::build->new()->run(@ARGV);
}
elsif ($command eq 'list-installed') {
    App::stew::cmd::list_installed->new()->run(@ARGV);
}
elsif ($command eq 'uninstall') {
    App::stew::cmd::uninstall->new()->run(@ARGV);
}
elsif ($command eq 'exec') {
    App::stew::cmd::exec->new()->run(@ARGV);
}
else {
    error qq{Unknown command '$command'};
}
